services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "make migrate && make run-server"
    tty: true
    env_file:
      - .env
    ports:
      - "${BACKEND_SERVER__PORT}:${BACKEND_SERVER__PORT}"